### ISSUE TITLE
First review of strings

### ISSUE THREAD

**Issue by Delphine** [mozilla-l10n/lockwiseios-l10n#4]
@joeyg: Thanks for taking a first pass at these strings :)

I've done an initial l10n-PM review of [the current strings in master](https://github.com/joeyg/lockwiseios-l10n/blob/master/en-US/lockwise-ios.xliff), mostly based on our [localization best practices](https://developer.mozilla.org/en-US/docs/Mozilla/Localization/Localization_content_best_practices). Let's tackle those first before I plunge in more. I've listed them by string ID:

- [x] "autofill.enabling": Punctuation should be an ellipsis instead of three dots (needs to be updates in other strings later on too)
- [x] "autofill.enabling": Should "AutoFill" be localizable? If not, this should be called out in comments or replaced by a placeholder, like it's done with the app name
- [x] "autofill.finished_enabling":  shouldn’t it be "AutoFill" like the string above? It's currently "autofill" in this one, so not consistent 
- [x] "not_using_passcode": apostrophes (and quotes) should always be curly in strings. Please double check throughout the file
- [x] "lockbox-ios/Storyboard/Base.lproj/AccountSetting.storyboard" datatype="plaintext" source-language="en" and until the end of the file: This is where I'm really not sure if we can use these. We've never used Storyboards in our iOS projects and Pontoon doesn't support this (CC @pike for confirmation). I think this should be dropped from the strings file, but let's double check about all this.

To sum things up - and before we can expose strings on Pontoon - another review on these strings based on l10n best practices would be suitable.  Then I can continue reviewing the output. 
We also need clarity on the Storyboards section.

Not sure who's on the hook to fix these strings, so CC @devinreams so he can possibly help assign :)

---

Also todo:

- [ ] can you create a German de/lockwise-ios.xliff from the templates, no translations?

- [ ] Side notes, the strings from https://github.com/mozilla-lockbox/lockbox-ios/blob/6abc1130339c8d4003274353c25844306a30e211/Shared/Common/Resources/BaseConstants.swift#L60-L73 seem to be duplicated in the xliff file. Can we make it so that these only need to be translated once?

- [ ] And should https://github.com/mozilla-lockbox/lockbox-ios/blob/6abc1130339c8d4003274353c25844306a30e211/Shared/Common/Resources/BaseConstants.swift#L67 be localized at all?

**Comment by Pike** [comment]
We should just try this on Pontoon stage. @joeyg, can you create a German `de/lockwise-ios.xliff` from the templates, no translations? Also invite @mozilla-pontoon as a collaborator?

Side notes, the strings from https://github.com/mozilla-lockbox/lockbox-ios/blob/6abc1130339c8d4003274353c25844306a30e211/Shared/Common/Resources/BaseConstants.swift#L60-L73 seem to be duplicated in the xliff file. Can we make it so that these only need to be translated once?

And should https://github.com/mozilla-lockbox/lockbox-ios/blob/6abc1130339c8d4003274353c25844306a30e211/Shared/Common/Resources/BaseConstants.swift#L67 be localized at all?

**Comment by joeyg** [comment]
Thanks! I’ll make these changes

**Comment by devinreams** [comment]
>I've done an initial l10n-PM review of the current strings in master, mostly based on our localization best practices. Let's tackle those first before I plunge in more.

I've drafted a PR that we can collaborate on over here with the changes in-code (won't appear here until the export is re-run): https://github.com/mozilla-lockbox/lockbox-ios/pull/952


>We've never used Storyboards in our iOS projects and Pontoon doesn't support this

For release timing purposes, we're likely going to bypass Pontoon for this first round.

But would still be curious to see if Pontoon on stage works (once a German version is created) with these storyboard strings...

---

Two other notes:

1. I updated the todo list up above with what I think are all the "to dos" requested here.
2. This repo has moved into the mozilla-l10n repo so new permissions/ownership exists

**Comment by Pike** [comment]
I tested pontoon on stage and got it commit back to this repo. I think that works as expected.

**Comment by devinreams** [comment]
See related PR for the dupes:
https://github.com/mozilla-lockwise/lockwise-ios/pull/959

**Comment by devinreams** [comment]
And the actual resulting export now here in this repo:
https://github.com/mozilla-l10n/lockwiseios-l10n/pull/6
